inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Style/VariableNumber:
  EnforcedStyle: snake_case

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
