default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sapwood_development

test:
  <<: *default
  database: sapwood_test

production:
  <<: *default
  database: [db_name]
  username: [db_username]
  password: [db_password]
