#
# --------------------
# Sapwood Config
# --------------------
#
# This is the configuration for your application. Set all of the values below
# with your settings.
#

# The base url of your application
url: http://localhost:3000

# Email address you want notifications coming from
default_from: Sapwood <noreply@example.com>

# Your SendGrid credentials (for sending emails)
send_grid:
  user_name:  user
  password:   password
  domain:     example.com
